version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies"
      - chmod +x ./gradlew
  build:
    commands:
      - echo "Starting build"
      - ./gradlew clean assembleDebug
artifacts:
  files:
    - app/build/outputs/apk/debug/app-debug.apk
  discard-paths: yes
