version: 0.2

phases:
  install:
    commands:
      - echo "Install started"
      - chmod +x ./gradlew
  build:
    commands:
      - echo "Build started"
      - ./gradlew clean assembleDebug
artifacts:
  files:
    - app/build/outputs/apk/debug/app-debug.apk
  discard-paths: yes
